approvedGitRepositories:
  - "**"

enableGlobalCache: false

enableScripts: true

nodeLinker: pnp

npmMinimalAgeGate: 0

npmRegistryServer: "https://registry.npmjs.org"

pnpEnableEsmLoader: false

yarnPath: .yarn/releases/yarn-4.18.1.cjs
